apiVersion: v1
kind: Service
metadata:
  name: bike-parking-service
spec:
  selector:
    app: bike-parking-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort 
